---
language: go
go:
  - "1.10"
  
services:
  - docker

env:
  global:
    - IMAGE="fleaz/cpthook"
    - COMMIT=${TRAVIS_COMMIT::8}

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh  
  - dep ensure

script:
  - cp cpthook.yml.example cpthook.yml
  - go test
  - CGO_ENABLED="0" GOARCH="amd64" GOOS="linux" go build -a -installsuffix cgo -o CptHook
  - docker build -f Dockerfile -t $IMAGE .

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh stable
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh development
    on:
      branch: development

notifications:
  webhooks:
    urls:
      - http://webhooks.rainbownerds.de:12345
    on_success: always # default: always
    on_failure: always # default: always
    on_start: always   # default: never
    on_cancel: always # default: always
    on_error: always # default: always

  email: false
